version: "3.9"
services:
  web:
    container-name: sringboot_app1
    build: .
    ports:
      - "8070-8080:8080"
      mysqldb:
    image: "mysql"
    ports:
      - 3307:3306
      environment:
        MYSQL_DATABASE: "test"
        MYSQL_ROOT_PASSWORD: "root"